/**
 * Pixel — a 2-listbox of natural numbers [m, n].
 *
 * In box form: {m}, {m, n}  =  em + em·en
 *
 * Pixels support a non-commutative associative multiplication:
 *   [m, n] · [p, q] = [m, q]  when n = p, otherwise nothing (null).
 *
 * This is exactly matrix index composition: think of [m, n] as the (m, n)
 * entry of a matrix. Multiplying [m, n] · [n, q] chains the indices,
 * reproducing matrix multiplication.
 *
 * Pythagorean parametrization (m > n ≥ 1, gcd(m,n) = 1, m and n not both odd):
 *   pixel [m, n]  →  (m² - n²,  2mn,  m² + n²)
 * This is the classical Babylonian / Pythagorean triple formula, made concrete
 * as a property of ordered pairs in Box Arithmetic.
 */
export class Pixel {
  readonly m: bigint;
  readonly n: bigint;

  constructor(m: bigint, n: bigint) {
    this.m = m;
    this.n = n;
  }

  /** [m, n] · [p, q] = [m, q] when n = p, else null (nothing) */
  pixelProduct(other: Pixel): Pixel | null {
    if (this.n !== other.m) return null;
    return new Pixel(this.m, other.n);
  }

  /** [m, n]^T = [n, m] */
  get transpose(): Pixel {
    return new Pixel(this.n, this.m);
  }

  /** Whether this pixel is diagonal (m = n) */
  get isDiagonal(): boolean {
    return this.m === this.n;
  }

  /**
   * Pythagorean triple generated by this pixel.
   * Requires m > n > 0.
   * Returns [a, b, c] where a² + b² = c².
   */
  pythagoreanTriple(): [bigint, bigint, bigint] | null {
    if (this.m <= this.n || this.n <= 0n) return null;
    const a = this.m * this.m - this.n * this.n;
    const b = 2n * this.m * this.n;
    const c = this.m * this.m + this.n * this.n;
    return [a, b, c];
  }

  toString(): string {
    return `[${this.m}, ${this.n}]`;
  }

  equals(other: Pixel): boolean {
    return this.m === other.m && this.n === other.n;
  }
}
